StorageBlobLogs
| where StatusCode == 200 or StatusText =~ "Success"
| extend IpAddr = extract(@"((?:\d{1,3}\.){3}\d{1,3}|(?:[a-fA-F0-9]{1,4}:){2,7}[a-fA-F0-9]{1,4})", 1, CallerIpAddress),
         Port = extract(@":(\d+)$", 1, CallerIpAddress)
| project-reorder
    TimeGenerated,
    AccountName,
    Protocol,
    IpAddr, Port,
    Location,
    OperationName,
    TlsVersion
| top 15 by TimeGenerated
